# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fits_pb2 as fits__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fits_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataServiceStub(object):
    """--- SERVICIO 1: METADATOS ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFileMetadata = channel.unary_unary(
                '/fits.MetadataService/GetFileMetadata',
                request_serializer=fits__pb2.MetadataRequest.SerializeToString,
                response_deserializer=fits__pb2.MetadataResponse.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """--- SERVICIO 1: METADATOS ---
    """

    def GetFileMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFileMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileMetadata,
                    request_deserializer=fits__pb2.MetadataRequest.FromString,
                    response_serializer=fits__pb2.MetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fits.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fits.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """--- SERVICIO 1: METADATOS ---
    """

    @staticmethod
    def GetFileMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fits.MetadataService/GetFileMetadata',
            fits__pb2.MetadataRequest.SerializeToString,
            fits__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImageServiceStub(object):
    """--- SERVICIO IMÁGENES ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImageData = channel.unary_unary(
                '/fits.ImageService/GetImageData',
                request_serializer=fits__pb2.ImageRequest.SerializeToString,
                response_deserializer=fits__pb2.ImageResponse.FromString,
                _registered_method=True)


class ImageServiceServicer(object):
    """--- SERVICIO IMÁGENES ---
    """

    def GetImageData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImageData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageData,
                    request_deserializer=fits__pb2.ImageRequest.FromString,
                    response_serializer=fits__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fits.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fits.ImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """--- SERVICIO IMÁGENES ---
    """

    @staticmethod
    def GetImageData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fits.ImageService/GetImageData',
            fits__pb2.ImageRequest.SerializeToString,
            fits__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
