# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fits.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fits.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfits.proto\x12\x04\x66its\"#\n\x0fMetadataRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"X\n\x10MetadataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\x07headers\x18\x03 \x03(\x0b\x32\x11.fits.HeaderEntry\":\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\" \n\x0cImageRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"D\n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t2S\n\x0fMetadataService\x12@\n\x0fGetFileMetadata\x12\x15.fits.MetadataRequest\x1a\x16.fits.MetadataResponse2G\n\x0cImageService\x12\x37\n\x0cGetImageData\x12\x12.fits.ImageRequest\x1a\x13.fits.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fits_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATAREQUEST']._serialized_start=20
  _globals['_METADATAREQUEST']._serialized_end=55
  _globals['_METADATARESPONSE']._serialized_start=57
  _globals['_METADATARESPONSE']._serialized_end=145
  _globals['_HEADERENTRY']._serialized_start=147
  _globals['_HEADERENTRY']._serialized_end=205
  _globals['_IMAGEREQUEST']._serialized_start=207
  _globals['_IMAGEREQUEST']._serialized_end=239
  _globals['_IMAGERESPONSE']._serialized_start=241
  _globals['_IMAGERESPONSE']._serialized_end=309
  _globals['_METADATASERVICE']._serialized_start=311
  _globals['_METADATASERVICE']._serialized_end=394
  _globals['_IMAGESERVICE']._serialized_start=396
  _globals['_IMAGESERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
